<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <CopyrightOwner Include="John Doe" Years="2021" />
    <Compile Update="SimplePack.cs" Pack="true" />
    <Content Include="SimplePack.bib" Pack="true" />
  </ItemGroup>

</Project>
