<Project Sdk="Belp.SDK.Build.Testing.XUnit/1.1.0">

  <!-- Compiler Configuration -->
  <ItemGroup>
    <Using Include="FluentAssertions" />
    <Using Include="FluentAssertions.Execution" />
  </ItemGroup>



  <!-- Dependencies -->
  <ItemGroup>
    <!-- DO NOT UPDATE -->
    <!-- DO NOT UPDATE -->
    <!-- DO NOT UPDATE -->
    <!-- DO NOT UPDATE -->
    <!-- DO NOT UPDATE -->
    <!-- DO NOT UPDATE -->
    <!-- DO NOT UPDATE -->
    <!-- DO NOT UPDATE -->
    <!-- DO NOT UPDATE -->
    <!-- DO NOT UPDATE -->
    <!-- DO NOT UPDATE -->
    <!-- DO NOT UPDATE -->
    <!-- DO NOT UPDATE -->
    <!-- DO NOT UPDATE -->
    <PackageReference Include="FluentAssertions" Version="7.2.0" />
    <PackageReference Include="FluentAssertions.Analyzers" Version="0.34.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <TestProjectReference Include="../../src/Belp.Build.Packinf/Belp.Build.Packinf.csproj" Alias="ThisPackage" />
  </ItemGroup>

</Project>
