<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net7.0;net8.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <CopyrightOwner Include="John Doe" Years="2021" />
    <Compile Include="Project.cs" Pack="true" Condition="'$(TargetFramework)' == ''" />
    <Content Include="Project.bib" Pack="true" />
  </ItemGroup>

</Project>
