<Project Sdk="Belp.SDK.PackOnly/0.5.0">

  <!-- Build Configuration -->
  <PropertyGroup>
    <ReferencePackinf>false</ReferencePackinf>
  </PropertyGroup>



  <!-- Package Information -->
  <PropertyGroup>
    <AddMetapackagePlaceholderLibrary>true</AddMetapackagePlaceholderLibrary>
    <Description>A package that extends MSBuild to make it easier to make NuGet packages.</Description>
    <DevelopmentDependency>true</DevelopmentDependency>
    <DisableAutoasmver>true</DisableAutoasmver>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/Arthri/Belp.Build.Packinf/</PackageProjectUrl>
    <PackageTags>msbuild</PackageTags>
    <Product>Belp</Product>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <Title>Packinf</Title>
    <Version Condition="'$(Version)' == ''">0.0.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <CopyrightOwner Include="Arthri" Years="2023, 2024, 2025, 2026" />
  </ItemGroup>

</Project>
