<Project ToolsVersion="15.0" TreatAsLocalProperty="_DirectoryBuildTargetsFile" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <!-- Load higher-up Directory.Build.targets if it exists -->
  <PropertyGroup>
    <_DirectoryBuildTargetsFile>$([MSBuild]::GetPathOfFileAbove('Directory.Build.targets', '$(MSBuildThisFileDirectory)../'))</_DirectoryBuildTargetsFile>
  </PropertyGroup>

  <Import Condition="Exists($(_DirectoryBuildTargetsFile))" Project="$(_DirectoryBuildTargetsFile)" />



  <Import Project="Assets/build/_Package.targets" />

</Project>
