<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <CopyrightOwner Include="John Doe" Years="2021" />
    <Content Include="a.txt" Pack="true" />
    <None Update="b.html" Pack="true" PackagePath="content/%(Filename)%(Extension)" />
    <None Update="c.rtf" Pack="true" PackagePath="contentFiles/%(Filename)%(Extension)" />
    <None Update="d.md" Pack="true" PackagePath="tools/%(Filename)%(Extension)" />
  </ItemGroup>

</Project>
