name: Continuous Integration

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    uses: Arthri/build-dotnet/.github/workflows/i.yml@v1
    permissions:
      contents: read
  format:
    needs: build
    uses: Arthri/format-dotnet/.github/workflows/i.yml@v1
    permissions:
      contents: read
  test:
    needs: format
    uses: Arthri/test-dotnet/.github/workflows/i.yml@v1
    permissions:
      contents: read
